name: Prod Apply

on: 
  workflow_dispatch:

env:
  ARM_ACCESS_KEY: ${{ secrets.AzStorageKey }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.sub }}
  ARM_TENANT_ID: ${{ secrets.tenantId }}
  ARM_CLIENT_ID: ${{ secrets.clientId }}
  ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}

jobs:
  terraform_workflow:
    name: terraform_workflow
    runs-on: ubuntu-laprod
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.14.2
          terraform_wrapper: false
      - name: init
        run: |
          terraform init \
            -backend-config=key=prod.terraform.tfstate \
            -backend-config=container_name=tfstate \
            -backend-config=resource_group_name=kja-rg \
            -backend-config=storage_account_name=kjastorage \
            -input=false
      - name: validate
        run: |
          terraform validate
      - name: plan
        run: |
          terraform plan -input=false -out prod.tfplan -var-file env/prod.tfvars
      - name: terraform apply
        run: |
          terraform apply -input=false prod.tfplan