name: Azure Plan

on: 
  workflow_dispatch:

env:
  ARM_ACCESS_KEY: ${{ secrets.AzStorageKey }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.sub }}
  ARM_TENANT_ID: ${{ secrets.tenantId }}
  ARM_CLIENT_ID: ${{ secrets.clientId }}
  ARM_CLIENT_SECRET: ${{ secrets.clientSecret }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: "Checkout"
      uses: actions/checkout@master
      
    - name: "Terraform Init"
      uses: hashicorp/terraform-github-actions@master
      with:
       tf_actions_version: 0.13.4
       tf_actions_subcommand: "init"

    - name: "Terraform Plan"
      uses: hashicorp/terraform-github-actions@master
      with:
       tf_actions_version: 0.13.4
       tf_actions_subcommand: "plan"